/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'organizationId' : [] | [bigint],
  'bodyContent' : string,
  'title' : string,
  'isPublished' : boolean,
  'imageBlobIds' : Array<string>,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'author' : string,
  'isFeatured' : boolean,
  'publicationDate' : string,
  'excerpt' : string,
  'authorPrincipal' : [] | [Principal],
}
export interface ArticleSubmission {
  'submittedAt' : [] | [bigint],
  'submissionStatus' : SubmissionStatus,
  'articleId' : bigint,
  'rejectionNote' : [] | [string],
}
export interface Comment {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'articleId' : bigint,
  'authorPrincipal' : Principal,
}
export interface OrgInvite {
  'status' : OrgInviteStatus,
  'orgId' : bigint,
  'inviteId' : bigint,
  'createdAt' : bigint,
  'invitedPrincipal' : Principal,
  'invitedByPrincipal' : Principal,
}
export type OrgInviteStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface OrgMembership {
  'orgId' : bigint,
  'memberPrincipal' : Principal,
  'joinedAt' : bigint,
}
export interface OrgSection {
  'id' : bigint,
  'bannerBlobId' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'slug' : string,
  'description' : string,
  'logoBlobId' : [] | [string],
}
export type SubmissionStatus = { 'pending_review' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface SubmissionWithArticle {
  'article' : Article,
  'submission' : ArticleSubmission,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'orgId' : [] | [bigint],
  'name' : string,
  'avatarBlobId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'approveArticleSubmission' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimSuperAdmin' : ActorMethod<[], undefined>,
  'createArticle' : ActorMethod<
    [
      string,
      string,
      [] | [Principal],
      [] | [bigint],
      string,
      Array<string>,
      string,
      Array<string>,
    ],
    bigint
  >,
  'createOrg' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    bigint
  >,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteOrg' : ActorMethod<[bigint], undefined>,
  'featureArticle' : ActorMethod<[bigint], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getArticleById' : ActorMethod<[bigint], Article>,
  'getArticlesByOrg' : ActorMethod<[bigint], Array<Article>>,
  'getArticlesByTag' : ActorMethod<[string], Array<Article>>,
  'getAuthorArticles' : ActorMethod<[Principal], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByArticle' : ActorMethod<[bigint], Array<Comment>>,
  'getFeaturedArticle' : ActorMethod<[], [] | [Article]>,
  'getMyInvites' : ActorMethod<[], Array<OrgInvite>>,
  'getMyMemberships' : ActorMethod<[], Array<OrgMembership>>,
  'getMyOrgs' : ActorMethod<[], Array<OrgSection>>,
  'getMySubmissions' : ActorMethod<[], Array<SubmissionWithArticle>>,
  'getOrgArticles' : ActorMethod<[bigint], Array<Article>>,
  'getOrgById' : ActorMethod<[bigint], [] | [OrgSection]>,
  'getOrgMembers' : ActorMethod<[bigint], Array<OrgMembership>>,
  'getOrgs' : ActorMethod<[], Array<OrgSection>>,
  'getPendingSubmissions' : ActorMethod<[bigint], Array<SubmissionWithArticle>>,
  'getPublishedArticles' : ActorMethod<[], Array<Article>>,
  'getSuperAdmin' : ActorMethod<[], [] | [Principal]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'inviteUserToOrg' : ActorMethod<[bigint, Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOrgMember' : ActorMethod<[bigint, Principal], boolean>,
  'publishArticle' : ActorMethod<[bigint], undefined>,
  'rejectArticleSubmission' : ActorMethod<[bigint, [] | [string]], undefined>,
  'removeOrgMember' : ActorMethod<[bigint, Principal], undefined>,
  'respondToOrgInvite' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchArticles' : ActorMethod<[string], Array<Article>>,
  'submitArticleForReview' : ActorMethod<[bigint], undefined>,
  'unfeatureArticle' : ActorMethod<[bigint], undefined>,
  'unpublishArticle' : ActorMethod<[bigint], undefined>,
  'updateArticle' : ActorMethod<
    [
      bigint,
      string,
      string,
      [] | [bigint],
      string,
      Array<string>,
      string,
      Array<string>,
    ],
    undefined
  >,
  'updateOrg' : ActorMethod<
    [bigint, string, string, string, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];