/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'organizationId' : IDL.Opt(IDL.Nat),
  'bodyContent' : IDL.Text,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'imageBlobIds' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'publicationDate' : IDL.Text,
  'excerpt' : IDL.Text,
  'authorPrincipal' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'orgId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'avatarBlobId' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'articleId' : IDL.Nat,
  'authorPrincipal' : IDL.Principal,
});
export const OrgInviteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const OrgInvite = IDL.Record({
  'status' : OrgInviteStatus,
  'orgId' : IDL.Nat,
  'inviteId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'invitedPrincipal' : IDL.Principal,
  'invitedByPrincipal' : IDL.Principal,
});
export const OrgMembership = IDL.Record({
  'orgId' : IDL.Nat,
  'memberPrincipal' : IDL.Principal,
  'joinedAt' : IDL.Int,
});
export const OrgSection = IDL.Record({
  'id' : IDL.Nat,
  'bannerBlobId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'logoBlobId' : IDL.Opt(IDL.Text),
});
export const SubmissionStatus = IDL.Variant({
  'pending_review' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const ArticleSubmission = IDL.Record({
  'submittedAt' : IDL.Opt(IDL.Int),
  'submissionStatus' : SubmissionStatus,
  'articleId' : IDL.Nat,
  'rejectionNote' : IDL.Opt(IDL.Text),
});
export const SubmissionWithArticle = IDL.Record({
  'article' : Article,
  'submission' : ArticleSubmission,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'approveArticleSubmission' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimSuperAdmin' : IDL.Func([], [], []),
  'createArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createOrg' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteOrg' : IDL.Func([IDL.Nat], [], []),
  'featureArticle' : IDL.Func([IDL.Nat], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticlesByOrg' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getArticlesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getAuthorArticles' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByArticle' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFeaturedArticle' : IDL.Func([], [IDL.Opt(Article)], ['query']),
  'getMyInvites' : IDL.Func([], [IDL.Vec(OrgInvite)], ['query']),
  'getMyMemberships' : IDL.Func([], [IDL.Vec(OrgMembership)], ['query']),
  'getMyOrgs' : IDL.Func([], [IDL.Vec(OrgSection)], ['query']),
  'getMySubmissions' : IDL.Func(
      [],
      [IDL.Vec(SubmissionWithArticle)],
      ['query'],
    ),
  'getOrgArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getOrgById' : IDL.Func([IDL.Nat], [IDL.Opt(OrgSection)], ['query']),
  'getOrgMembers' : IDL.Func([IDL.Nat], [IDL.Vec(OrgMembership)], ['query']),
  'getOrgs' : IDL.Func([], [IDL.Vec(OrgSection)], ['query']),
  'getPendingSubmissions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SubmissionWithArticle)],
      ['query'],
    ),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getSuperAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'inviteUserToOrg' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOrgMember' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
  'publishArticle' : IDL.Func([IDL.Nat], [], []),
  'rejectArticleSubmission' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'removeOrgMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'respondToOrgInvite' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'submitArticleForReview' : IDL.Func([IDL.Nat], [], []),
  'unfeatureArticle' : IDL.Func([IDL.Nat], [], []),
  'unpublishArticle' : IDL.Func([IDL.Nat], [], []),
  'updateArticle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateOrg' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'organizationId' : IDL.Opt(IDL.Nat),
    'bodyContent' : IDL.Text,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'imageBlobIds' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'publicationDate' : IDL.Text,
    'excerpt' : IDL.Text,
    'authorPrincipal' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'orgId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'avatarBlobId' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'articleId' : IDL.Nat,
    'authorPrincipal' : IDL.Principal,
  });
  const OrgInviteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const OrgInvite = IDL.Record({
    'status' : OrgInviteStatus,
    'orgId' : IDL.Nat,
    'inviteId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'invitedPrincipal' : IDL.Principal,
    'invitedByPrincipal' : IDL.Principal,
  });
  const OrgMembership = IDL.Record({
    'orgId' : IDL.Nat,
    'memberPrincipal' : IDL.Principal,
    'joinedAt' : IDL.Int,
  });
  const OrgSection = IDL.Record({
    'id' : IDL.Nat,
    'bannerBlobId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'logoBlobId' : IDL.Opt(IDL.Text),
  });
  const SubmissionStatus = IDL.Variant({
    'pending_review' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ArticleSubmission = IDL.Record({
    'submittedAt' : IDL.Opt(IDL.Int),
    'submissionStatus' : SubmissionStatus,
    'articleId' : IDL.Nat,
    'rejectionNote' : IDL.Opt(IDL.Text),
  });
  const SubmissionWithArticle = IDL.Record({
    'article' : Article,
    'submission' : ArticleSubmission,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'approveArticleSubmission' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimSuperAdmin' : IDL.Func([], [], []),
    'createArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createOrg' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteOrg' : IDL.Func([IDL.Nat], [], []),
    'featureArticle' : IDL.Func([IDL.Nat], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticlesByOrg' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getArticlesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'getAuthorArticles' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByArticle' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFeaturedArticle' : IDL.Func([], [IDL.Opt(Article)], ['query']),
    'getMyInvites' : IDL.Func([], [IDL.Vec(OrgInvite)], ['query']),
    'getMyMemberships' : IDL.Func([], [IDL.Vec(OrgMembership)], ['query']),
    'getMyOrgs' : IDL.Func([], [IDL.Vec(OrgSection)], ['query']),
    'getMySubmissions' : IDL.Func(
        [],
        [IDL.Vec(SubmissionWithArticle)],
        ['query'],
      ),
    'getOrgArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getOrgById' : IDL.Func([IDL.Nat], [IDL.Opt(OrgSection)], ['query']),
    'getOrgMembers' : IDL.Func([IDL.Nat], [IDL.Vec(OrgMembership)], ['query']),
    'getOrgs' : IDL.Func([], [IDL.Vec(OrgSection)], ['query']),
    'getPendingSubmissions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SubmissionWithArticle)],
        ['query'],
      ),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getSuperAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'inviteUserToOrg' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOrgMember' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
    'publishArticle' : IDL.Func([IDL.Nat], [], []),
    'rejectArticleSubmission' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'removeOrgMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'respondToOrgInvite' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'submitArticleForReview' : IDL.Func([IDL.Nat], [], []),
    'unfeatureArticle' : IDL.Func([IDL.Nat], [], []),
    'unpublishArticle' : IDL.Func([IDL.Nat], [], []),
    'updateArticle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateOrg' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };