/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'organizationId' : IDL.Opt(IDL.Nat),
  'bodyContent' : IDL.Text,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'publicationDate' : IDL.Text,
  'heroImageBlobId2' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'heroImageBlobId' : IDL.Opt(IDL.Text),
  'authorPrincipal' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'orgId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'avatarBlobId' : IDL.Opt(IDL.Text),
});
export const OrgSection = IDL.Record({
  'id' : IDL.Nat,
  'bannerBlobId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'logoBlobId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createOrg' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteOrg' : IDL.Func([IDL.Nat], [], []),
  'featureArticle' : IDL.Func([IDL.Nat], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticlesByOrg' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'getArticlesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getAuthorArticles' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedArticle' : IDL.Func([], [IDL.Opt(Article)], ['query']),
  'getOrgById' : IDL.Func([IDL.Nat], [OrgSection], ['query']),
  'getOrgs' : IDL.Func([], [IDL.Vec(OrgSection)], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishArticle' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'unfeatureArticle' : IDL.Func([IDL.Nat], [], []),
  'unpublishArticle' : IDL.Func([IDL.Nat], [], []),
  'updateArticle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateOrg' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'organizationId' : IDL.Opt(IDL.Nat),
    'bodyContent' : IDL.Text,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'publicationDate' : IDL.Text,
    'heroImageBlobId2' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'heroImageBlobId' : IDL.Opt(IDL.Text),
    'authorPrincipal' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'orgId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'avatarBlobId' : IDL.Opt(IDL.Text),
  });
  const OrgSection = IDL.Record({
    'id' : IDL.Nat,
    'bannerBlobId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'logoBlobId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createOrg' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteOrg' : IDL.Func([IDL.Nat], [], []),
    'featureArticle' : IDL.Func([IDL.Nat], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticlesByOrg' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'getArticlesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'getAuthorArticles' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedArticle' : IDL.Func([], [IDL.Opt(Article)], ['query']),
    'getOrgById' : IDL.Func([IDL.Nat], [OrgSection], ['query']),
    'getOrgs' : IDL.Func([], [IDL.Vec(OrgSection)], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishArticle' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'unfeatureArticle' : IDL.Func([IDL.Nat], [], []),
    'unpublishArticle' : IDL.Func([IDL.Nat], [], []),
    'updateArticle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateOrg' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };