/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ArticleSubmission {
    submittedAt?: bigint;
    submissionStatus: SubmissionStatus;
    articleId: bigint;
    rejectionNote?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface OrgInvite {
    status: OrgInviteStatus;
    orgId: bigint;
    inviteId: bigint;
    createdAt: bigint;
    invitedPrincipal: Principal;
    invitedByPrincipal: Principal;
}
export interface Comment {
    id: bigint;
    body: string;
    createdAt: bigint;
    authorName: string;
    articleId: bigint;
    authorPrincipal: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SubmissionWithArticle {
    article: Article;
    submission: ArticleSubmission;
}
export interface OrgSection {
    id: bigint;
    bannerBlobId?: string;
    name: string;
    createdAt: bigint;
    slug: string;
    description: string;
    logoBlobId?: string;
}
export interface OrgMembership {
    orgId: bigint;
    memberPrincipal: Principal;
    joinedAt: bigint;
}
export interface Article {
    id: bigint;
    organizationId?: bigint;
    bodyContent: string;
    title: string;
    isPublished: boolean;
    imageBlobIds: Array<string>;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    isFeatured: boolean;
    publicationDate: string;
    excerpt: string;
    authorPrincipal?: Principal;
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    orgId?: bigint;
    name: string;
    avatarBlobId?: string;
}
export enum OrgInviteStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum SubmissionStatus {
    pending_review = "pending_review",
    rejected = "rejected",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(articleId: bigint, body: string): Promise<void>;
    approveArticleSubmission(articleId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimSuperAdmin(): Promise<void>;
    createArticle(title: string, author: string, authorPrincipal: Principal | null, organizationId: bigint | null, publicationDate: string, imageBlobIds: Array<string>, bodyContent: string, tags: Array<string>): Promise<bigint>;
    createOrg(name: string, slug: string, description: string, logoBlobId: string | null, bannerBlobId: string | null): Promise<bigint>;
    deleteArticle(articleId: bigint): Promise<void>;
    deleteComment(commentId: bigint): Promise<void>;
    deleteOrg(orgId: bigint): Promise<void>;
    featureArticle(articleId: bigint): Promise<void>;
    getAllArticles(): Promise<Array<Article>>;
    getArticleById(articleId: bigint): Promise<Article>;
    getArticlesByOrg(orgId: bigint): Promise<Array<Article>>;
    getArticlesByTag(tag: string): Promise<Array<Article>>;
    getAuthorArticles(authorPrincipal: Principal): Promise<Array<Article>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentsByArticle(articleId: bigint): Promise<Array<Comment>>;
    getMyInvites(): Promise<Array<OrgInvite>>;
    getMyMemberships(): Promise<Array<OrgMembership>>;
    getMyOrgs(): Promise<Array<OrgSection>>;
    getMySubmissions(): Promise<Array<SubmissionWithArticle>>;
    getOrgArticles(orgId: bigint): Promise<Array<Article>>;
    getOrgById(orgId: bigint): Promise<OrgSection | null>;
    getOrgMembers(orgId: bigint): Promise<Array<OrgMembership>>;
    getOrgs(): Promise<Array<OrgSection>>;
    getPendingSubmissions(orgId: bigint): Promise<Array<SubmissionWithArticle>>;
    getPublishedArticles(): Promise<Array<Article>>;
    getSuperAdmin(): Promise<Principal | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    inviteUserToOrg(orgId: bigint, userPrincipal: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isOrgMember(orgId: bigint, user: Principal): Promise<boolean>;
    publishArticle(articleId: bigint): Promise<void>;
    rejectArticleSubmission(articleId: bigint, note: string | null): Promise<void>;
    removeOrgMember(orgId: bigint, memberPrincipal: Principal): Promise<void>;
    respondToOrgInvite(inviteId: bigint, accept: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchArticles(queryText: string): Promise<Array<Article>>;
    submitArticleForReview(articleId: bigint): Promise<void>;
    unfeatureArticle(articleId: bigint): Promise<void>;
    unpublishArticle(articleId: bigint): Promise<void>;
    updateArticle(articleId: bigint, title: string, author: string, organizationId: bigint | null, publicationDate: string, imageBlobIds: Array<string>, bodyContent: string, tags: Array<string>): Promise<void>;
    updateOrg(orgId: bigint, name: string, slug: string, description: string, logoBlobId: string | null, bannerBlobId: string | null): Promise<void>;
    createPuzzle(puzzleType: PuzzleType, title: string, gridWidth: bigint, gridHeight: bigint, cells: Array<CrosswordCell>, clues: Array<CrosswordClue>): Promise<bigint>;
    updatePuzzle(id: bigint, title: string, gridWidth: bigint, gridHeight: bigint, cells: Array<CrosswordCell>, clues: Array<CrosswordClue>): Promise<void>;
    deletePuzzle(id: bigint): Promise<void>;
    getAllPuzzles(): Promise<Array<Puzzle>>;
    getActivePuzzle(puzzleType: PuzzleType): Promise<Puzzle | null>;
    setActivePuzzle(id: bigint): Promise<void>;
}
import type { Article as _Article, ArticleSubmission as _ArticleSubmission, OrgInvite as _OrgInvite, OrgInviteStatus as _OrgInviteStatus, OrgSection as _OrgSection, SubmissionStatus as _SubmissionStatus, SubmissionWithArticle as _SubmissionWithArticle, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
// Raw Candid puzzle types
type _ClueDirection = { across: null } | { down: null };
type _PuzzleType = { mini: null } | { standard: null };
type _CrosswordCell = { letter: string; isBlack: boolean; number: [] | [bigint] };
type _CrosswordClue = { number: bigint; direction: _ClueDirection; clue: string; answer: string; startRow: bigint; startCol: bigint; length: bigint };
type _Puzzle = { id: bigint; puzzleType: _PuzzleType; title: string; gridWidth: bigint; gridHeight: bigint; cells: Array<_CrosswordCell>; clues: Array<_CrosswordClue>; isActive: boolean; createdAt: bigint; publishedAt: [] | [bigint]; createdBy: any };
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async approveArticleSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveArticleSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveArticleSubmission(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimSuperAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimSuperAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimSuperAdmin();
            return result;
        }
    }
    async createArticle(arg0: string, arg1: string, arg2: Principal | null, arg3: bigint | null, arg4: string, arg5: Array<string>, arg6: string, arg7: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createOrg(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrg(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrg(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteOrg(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrg(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrg(arg0);
            return result;
        }
    }
    async featureArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.featureArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.featureArticle(arg0);
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleById(arg0: bigint): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleById(arg0);
                return from_candid_Article_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleById(arg0);
            return from_candid_Article_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlesByOrg(arg0: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByOrg(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByOrg(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlesByTag(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByTag(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByTag(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthorArticles(arg0: Principal): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthorArticles(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthorArticles(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsByArticle(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByArticle(arg0);
            return result;
        }
    }
    async getMyInvites(): Promise<Array<OrgInvite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvites();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvites();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMemberships(): Promise<Array<OrgMembership>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMemberships();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMemberships();
            return result;
        }
    }
    async getMyOrgs(): Promise<Array<OrgSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrgs();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrgs();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmissions(): Promise<Array<SubmissionWithArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrgArticles(arg0: bigint): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrgArticles(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrgArticles(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrgById(arg0: bigint): Promise<OrgSection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrgById(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrgById(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrgMembers(arg0: bigint): Promise<Array<OrgMembership>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrgMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrgMembers(arg0);
            return result;
        }
    }
    async getOrgs(): Promise<Array<OrgSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrgs();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrgs();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingSubmissions(arg0: bigint): Promise<Array<SubmissionWithArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingSubmissions(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingSubmissions(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedArticles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedArticles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuperAdmin(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuperAdmin();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuperAdmin();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteUserToOrg(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteUserToOrg(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteUserToOrg(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOrgMember(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOrgMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOrgMember(arg0, arg1);
            return result;
        }
    }
    async publishArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishArticle(arg0);
            return result;
        }
    }
    async rejectArticleSubmission(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectArticleSubmission(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectArticleSubmission(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async removeOrgMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeOrgMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeOrgMember(arg0, arg1);
            return result;
        }
    }
    async respondToOrgInvite(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToOrgInvite(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToOrgInvite(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchArticles(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArticles(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArticles(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitArticleForReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitArticleForReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitArticleForReview(arg0);
            return result;
        }
    }
    async unfeatureArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfeatureArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfeatureArticle(arg0);
            return result;
        }
    }
    async unpublishArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishArticle(arg0);
            return result;
        }
    }
    async updateArticle(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null, arg4: string, arg5: Array<string>, arg6: string, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateOrg(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrg(arg0, arg1, arg2, arg3, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrg(arg0, arg1, arg2, arg3, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createPuzzle(arg0, arg1, arg2, arg3, arg4, arg5) {
        const rawType = to_candid_puzzle_type(arg0);
        const rawCells = arg4.map(to_candid_crossword_cell);
        const rawClues = arg5.map(to_candid_crossword_clue);
        if (this.processError) {
            try {
                return await this.actor.createPuzzle(rawType, arg1, arg2, arg3, rawCells, rawClues);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.createPuzzle(rawType, arg1, arg2, arg3, rawCells, rawClues);
        }
    }
    async updatePuzzle(arg0, arg1, arg2, arg3, arg4, arg5) {
        const rawCells = arg4.map(to_candid_crossword_cell);
        const rawClues = arg5.map(to_candid_crossword_clue);
        if (this.processError) {
            try {
                return await this.actor.updatePuzzle(arg0, arg1, arg2, arg3, rawCells, rawClues);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.updatePuzzle(arg0, arg1, arg2, arg3, rawCells, rawClues);
        }
    }
    async deletePuzzle(arg0) {
        if (this.processError) {
            try {
                return await this.actor.deletePuzzle(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.deletePuzzle(arg0);
        }
    }
    async getAllPuzzles() {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPuzzles();
                return result.map(from_candid_puzzle);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPuzzles();
            return result.map(from_candid_puzzle);
        }
    }
    async getActivePuzzle(arg0) {
        const rawType = to_candid_puzzle_type(arg0);
        if (this.processError) {
            try {
                const result = await this.actor.getActivePuzzle(rawType);
                return result.length > 0 ? from_candid_puzzle(result[0]) : null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePuzzle(rawType);
            return result.length > 0 ? from_candid_puzzle(result[0]) : null;
        }
    }
    async setActivePuzzle(arg0) {
        if (this.processError) {
            try {
                return await this.actor.setActivePuzzle(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.setActivePuzzle(arg0);
        }
    }
}
function from_candid_ArticleSubmission_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleSubmission): ArticleSubmission {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Article_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrgInviteStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrgInviteStatus): OrgInviteStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_OrgInvite_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrgInvite): OrgInvite {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrgSection_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrgSection): OrgSection {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionWithArticle_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionWithArticle): SubmissionWithArticle {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrgSection]): OrgSection | null {
    return value.length === 0 ? null : from_candid_OrgSection_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    organizationId: [] | [bigint];
    bodyContent: string;
    title: string;
    isPublished: boolean;
    imageBlobIds: Array<string>;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    isFeatured: boolean;
    publicationDate: string;
    excerpt: string;
    authorPrincipal: [] | [Principal];
}): {
    id: bigint;
    organizationId?: bigint;
    bodyContent: string;
    title: string;
    isPublished: boolean;
    imageBlobIds: Array<string>;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    isFeatured: boolean;
    publicationDate: string;
    excerpt: string;
    authorPrincipal?: Principal;
} {
    return {
        id: value.id,
        organizationId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.organizationId)),
        bodyContent: value.bodyContent,
        title: value.title,
        isPublished: value.isPublished,
        imageBlobIds: value.imageBlobIds,
        createdAt: value.createdAt,
        tags: value.tags,
        author: value.author,
        isFeatured: value.isFeatured,
        publicationDate: value.publicationDate,
        excerpt: value.excerpt,
        authorPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.authorPrincipal))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    orgId: [] | [bigint];
    name: string;
    avatarBlobId: [] | [string];
}): {
    bio: string;
    principal: Principal;
    orgId?: bigint;
    name: string;
    avatarBlobId?: string;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        orgId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.orgId)),
        name: value.name,
        avatarBlobId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.avatarBlobId))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrgInviteStatus;
    orgId: bigint;
    inviteId: bigint;
    createdAt: bigint;
    invitedPrincipal: Principal;
    invitedByPrincipal: Principal;
}): {
    status: OrgInviteStatus;
    orgId: bigint;
    inviteId: bigint;
    createdAt: bigint;
    invitedPrincipal: Principal;
    invitedByPrincipal: Principal;
} {
    return {
        status: from_candid_OrgInviteStatus_n26(_uploadFile, _downloadFile, value.status),
        orgId: value.orgId,
        inviteId: value.inviteId,
        createdAt: value.createdAt,
        invitedPrincipal: value.invitedPrincipal,
        invitedByPrincipal: value.invitedByPrincipal
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bannerBlobId: [] | [string];
    name: string;
    createdAt: bigint;
    slug: string;
    description: string;
    logoBlobId: [] | [string];
}): {
    id: bigint;
    bannerBlobId?: string;
    name: string;
    createdAt: bigint;
    slug: string;
    description: string;
    logoBlobId?: string;
} {
    return {
        id: value.id,
        bannerBlobId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.bannerBlobId)),
        name: value.name,
        createdAt: value.createdAt,
        slug: value.slug,
        description: value.description,
        logoBlobId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.logoBlobId))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    article: _Article;
    submission: _ArticleSubmission;
}): {
    article: Article;
    submission: ArticleSubmission;
} {
    return {
        article: from_candid_Article_n14(_uploadFile, _downloadFile, value.article),
        submission: from_candid_ArticleSubmission_n34(_uploadFile, _downloadFile, value.submission)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submittedAt: [] | [bigint];
    submissionStatus: _SubmissionStatus;
    articleId: bigint;
    rejectionNote: [] | [string];
}): {
    submittedAt?: bigint;
    submissionStatus: SubmissionStatus;
    articleId: bigint;
    rejectionNote?: string;
} {
    return {
        submittedAt: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.submittedAt)),
        submissionStatus: from_candid_SubmissionStatus_n37(_uploadFile, _downloadFile, value.submissionStatus),
        articleId: value.articleId,
        rejectionNote: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.rejectionNote))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): OrgInviteStatus {
    return "pending" in value ? OrgInviteStatus.pending : "accepted" in value ? OrgInviteStatus.accepted : "declined" in value ? OrgInviteStatus.declined : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending_review: null;
} | {
    rejected: null;
} | {
    draft: null;
}): SubmissionStatus {
    return "pending_review" in value ? SubmissionStatus.pending_review : "rejected" in value ? SubmissionStatus.rejected : "draft" in value ? SubmissionStatus.draft : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrgInvite>): Array<OrgInvite> {
    return value.map((x)=>from_candid_OrgInvite_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrgSection>): Array<OrgSection> {
    return value.map((x)=>from_candid_OrgSection_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubmissionWithArticle>): Array<SubmissionWithArticle> {
    return value.map((x)=>from_candid_SubmissionWithArticle_n32(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    orgId?: bigint;
    name: string;
    avatarBlobId?: string;
}): {
    bio: string;
    principal: Principal;
    orgId: [] | [bigint];
    name: string;
    avatarBlobId: [] | [string];
} {
    return {
        bio: value.bio,
        principal: value.principal,
        orgId: value.orgId ? candid_some(value.orgId) : candid_none(),
        name: value.name,
        avatarBlobId: value.avatarBlobId ? candid_some(value.avatarBlobId) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
// --- Puzzle encoding/decoding helpers ---
function to_candid_puzzle_type(v) {
    return v === 'mini' ? { mini: null } : { standard: null };
}
function from_candid_puzzle_type(v) {
    return 'mini' in v ? 'mini' : 'standard';
}
function to_candid_clue_direction(v) {
    return v === 'across' ? { across: null } : { down: null };
}
function from_candid_clue_direction(v) {
    return 'across' in v ? 'across' : 'down';
}
function to_candid_crossword_cell(c) {
    return { letter: c.letter, isBlack: c.isBlack, number: c.number !== undefined && c.number !== null ? [c.number] : [] };
}
function from_candid_crossword_cell(c) {
    return { letter: c.letter, isBlack: c.isBlack, number: c.number.length > 0 ? c.number[0] : undefined };
}
function to_candid_crossword_clue(c) {
    return { number: c.number, direction: to_candid_clue_direction(c.direction), clue: c.clue, answer: c.answer, startRow: c.startRow, startCol: c.startCol, length: c.length };
}
function from_candid_crossword_clue(c) {
    return { number: c.number, direction: from_candid_clue_direction(c.direction), clue: c.clue, answer: c.answer, startRow: c.startRow, startCol: c.startCol, length: c.length };
}
function from_candid_puzzle(p) {
    return {
        id: p.id,
        puzzleType: from_candid_puzzle_type(p.puzzleType),
        title: p.title,
        gridWidth: p.gridWidth,
        gridHeight: p.gridHeight,
        cells: p.cells.map(from_candid_crossword_cell),
        clues: p.clues.map(from_candid_crossword_clue),
        isActive: p.isActive,
        createdAt: p.createdAt,
        publishedAt: p.publishedAt.length > 0 ? p.publishedAt[0] : undefined,
        createdBy: p.createdBy,
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
